---
abstract: 'Find URIs in arbitrary text'
author:
  - 'Michael G Schwern <schwern@pobox.com>'
build_requires:
  Module::Build: '0.30'
  Test::More: '0.88'
configure_requires:
  Module::Build: '0.30'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: URI-Find
provides:
  URI::Find:
    file: lib/URI/Find.pm
    version: '20140702'
  URI::Find::Schemeless:
    file: lib/URI/Find/Schemeless.pm
    version: '20140702'
requires:
  URI: '1.00'
  URI::URL: '5.00'
  perl: v5.6.0
resources:
  bugtracker: http://github.com/schwern/URI-Find/issues/
  homepage: http://search.cpan.org/dist/URI-Find
  license: http://dev.perl.org/licenses/
  repository: http://github.com/schwern/URI-Find/
version: '20140702'
